import { SidebarOptions } from 'vuepress-theme-hope';

export const sidebarZh: SidebarOptions = {
  '/0-wings/0h-prop-index': [
    '/1-silencer/1d-prop-silencer',
    '/2-faceless/2i-prop-faceless',
    '/2-faceless/2j-prop-flywave',
    '/2-faceless/2k-prop-jooq',
    '/3-slardar/3i-prop-slardar',
    '/3-slardar/3j-prop-webmvc',
    '/3-slardar/3k-prop-function',
    '/3-slardar/3l-prop-hazelcast',
    '/4-warlock/4d-prop-warlock',
    '/8-radiant/8b-prop-tinytask',
    '/8-radiant/8d-prop-tinymail',
  ],
  '/0-wings/': 'structure',
  '/1-silencer/': 'structure',
  '/2-faceless/': 'structure',
  '/3-slardar/': 'structure',
  '/4-warlock/': 'structure',
  '/5-batrider/': 'structure',
  '/8-radiant/': 'structure',
  '/9-example/': 'structure',
  '/a-mirana/': 'structure',
  '/b-meepo/': 'structure',
  '/': 'structure',
};

export const sidebarEn: SidebarOptions = {
  '/en/0-wings/0h-prop-index': [
    '/en/1-silencer/1d-prop-silencer',
    '/en/2-faceless/2i-prop-faceless',
    '/en/2-faceless/2j-prop-flywave',
    '/en/2-faceless/2k-prop-jooq',
    '/en/3-slardar/3i-prop-slardar',
    '/en/3-slardar/3j-prop-webmvc',
    '/en/3-slardar/3k-prop-function',
    '/en/3-slardar/3l-prop-hazelcast',
    '/en/4-warlock/4d-prop-warlock',
    '/en/8-radiant/8b-prop-tinytask',
    '/en/8-radiant/8d-prop-tinymail',
  ],
  '/en/0-wings/': 'structure',
  '/en/1-silencer/': 'structure',
  '/en/2-faceless/': 'structure',
  '/en/3-slardar/': 'structure',
  '/en/4-warlock/': 'structure',
  '/en/5-batrider/': 'structure',
  '/en/8-radiant/': 'structure',
  '/en/9-example/': 'structure',
  '/en/a-mirana/': 'structure',
  '/en/b-meepo/': 'structure',
  '/en/': 'structure',
};
